version: "3"
services:
  postgres:
    image: postgres:9.5.7
    volumes:
      - ../scripts/schema:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=abanking_db
      - POSTGRES_USER=abanking
      - POSTGRES_PASSWORD=abanking666
