/* 
 * Copyright (c) 2016 Anzen Soluciones S.A. de C.V.
 * Mexico D.F.
 * All rights reserved.
 * 
 * THIS SOFTWARE IS  CONFIDENTIAL INFORMATION PROPIETARY OF ANZEN SOLUCIONES.
 * THIS INFORMATION SHOULD NOT BE DISCLOSED AND MAY ONLY BE USED IN ACCORDANCE THE TERMS DETERMINED BY THE COMPANY ITSELF.
 */
-- start ccs_cred_params
CREATE SEQUENCE SQ_CCS_CRED_PARAMS_ID NO CYCLE;
CREATE TABLE CCS_CRED_PARAMS (
     CREDENTIAL_TYPE BIGINT PRIMARY KEY DEFAULT nextval('SQ_CCS_CRED_PARAMS_ID'), 
     CREDENTIAL_DESC VARCHAR(255), 
     MAX_FAILED_LOGINS NUMERIC(2) NOT NULL, 
     MAX_PWD_LENGTH NUMERIC(2) NOT NULL, 
     MIN_PWD_LENGTH NUMERIC(2) NOT NULL, 
     MIN_UNAME_LENGTH NUMERIC(2) NOT NULL, 
     MAX_UNAME_LENGTH NUMERIC(2) NOT NULL, 
     MAX_FAILED_OTP NUMERIC(2) NOT NULL
);
COMMENT ON COLUMN CCS_CRED_PARAMS.CREDENTIAL_TYPE IS 'must be one of the credential types defined in CCS_PROD_BUS_CRED//must be one credential type';
COMMENT ON COLUMN CCS_CRED_PARAMS.CREDENTIAL_DESC IS 'the description of this creedential type';
COMMENT ON COLUMN CCS_CRED_PARAMS.MAX_FAILED_LOGINS IS 'Maximum failed log ins before the master credential is locked';
COMMENT ON COLUMN CCS_CRED_PARAMS.MAX_PWD_LENGTH IS 'Maximum password length';
COMMENT ON COLUMN CCS_CRED_PARAMS.MIN_PWD_LENGTH IS 'Minimum password length';
COMMENT ON COLUMN CCS_CRED_PARAMS.MIN_UNAME_LENGTH IS 'Minimum user name length';
COMMENT ON COLUMN CCS_CRED_PARAMS.MAX_UNAME_LENGTH IS 'Maximum user name length';
-- end ccs_cred_params

-- start ccs_customer_mast
CREATE SEQUENCE SQ_CCS_CUSTOMER_MAST_ID NO CYCLE;
CREATE TABLE CCS_CUSTOMER_MAST (
     CUSTOMER_ID BIGINT PRIMARY KEY DEFAULT nextval('SQ_CCS_CUSTOMER_MAST_ID'), 
     CREDENTIAL_TYPE BIGINT NOT NULL, 
     LOGIN_NAME VARCHAR(255)  NOT NULL, 
     LAST_LOGIN_DATE DATE, 
     E_MAIL VARCHAR(400), 
     MASTER_PASSWORD VARCHAR(400) NOT NULL, 
     CREATE_DATE DATE NOT NULL, 
     CUSTOMER_MAST_STAT NUMERIC(1) NOT NULL, 
     ERROR_COUNT_FAILED_LOGINS NUMERIC(2), 
     LAST_FAILED_LOGIN_DATE DATE,
     
     CONSTRAINT CREDENTIAL_TYPE_FK FOREIGN KEY (CREDENTIAL_TYPE) REFERENCES CCS_CRED_PARAMS(CREDENTIAL_TYPE)
);
COMMENT ON COLUMN CCS_CUSTOMER_MAST.CUSTOMER_ID IS 'CCS customer id';
COMMENT ON COLUMN CCS_CUSTOMER_MAST.LOGIN_NAME IS 'The user name (case dependent)';
COMMENT ON COLUMN CCS_CUSTOMER_MAST.LAST_LOGIN_DATE IS 'The last log in date';
COMMENT ON COLUMN CCS_CUSTOMER_MAST.E_MAIL IS 'The users email';
COMMENT ON COLUMN CCS_CUSTOMER_MAST.MASTER_PASSWORD IS 'The encrypted master password';
COMMENT ON COLUMN CCS_CUSTOMER_MAST.CREATE_DATE IS 'The date this record was created';
COMMENT ON COLUMN CCS_CUSTOMER_MAST.CUSTOMER_MAST_STAT IS 'The status of this record:
0 - account is locked/desativated
1 - account is active
2 - account state where a temporary password is just generated
3 - account state where CCS awaits user to change temporary password to a permanent password
4 - account is inactive/deleted';
COMMENT ON COLUMN CCS_CUSTOMER_MAST.ERROR_COUNT_FAILED_LOGINS IS 'The number of failed log in attempts (i.e. wrong password)';
-- end ccs_customer_mast

-- start ccs_vip_token_id
CREATE TABLE CCS_VIP_TOKEN_ID (
    CUSTOMER_ID BIGINT NOT NULL,
    TOKEN_ID VARCHAR(255) NOT NULL,
    ALIAS_TOKEN_ID VARCHAR(255) NOT NULL,
    
    CONSTRAINT UNIQUE_CUSTOMER_ID UNIQUE (CUSTOMER_ID),
    CONSTRAINT UNIQUE_TOKEN_ID UNIQUE (TOKEN_ID),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CCS_CUSTOMER_MAST(CUSTOMER_ID)
);
COMMENT ON COLUMN CCS_VIP_TOKEN_ID.CUSTOMER_ID IS 'this is the id of ccs_customer_mast';
COMMENT ON COLUMN CCS_VIP_TOKEN_ID.TOKEN_ID IS 'this is the id of device what generates the otp';
COMMENT ON COLUMN CCS_VIP_TOKEN_ID.ALIAS_TOKEN_ID IS 'this is the name for token_id';
-- end ccs_vip_token_id
